### ISSUE TITLE
StratMap 2023 Land Parcels Ector\Harris [Data Update]

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/gio-data-update#98]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

Fields for Ector shp and gdb are not correct

**Data**
- [x] Data Processing [renaming file, data organization] per given naming convention @LaurenKirk 
- [x] Quality Assurance @LaurenKirk

**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba
- [x] Add zip to collection key @TNRIS/git-sba 

![Screenshot 2023-09-01 081249](https://github.com/TNRIS/tnris-data-update/assets/8459928/d8346c4a-c10c-4b99-8603-909a6d92e9b4)

**Comment by LaurenKirk** [comment]
@mitchellryant @ThorTheDestroyer Ector Parcels have been corrected and pushed back up to respective fgdb and shp folders on loading-dock/port-of-stratmap/parcels/final/

Having trouble accessing incoming data from CloudBerry.  Will reattempt to copy data over to that spot on network next week.

**Comment by LaurenKirk** [comment]
Re-opening.  Found some issues with Harris County.  Will review and resolve with Clayton.  This also serves as some practice for Clayton resolving issues in GitHub. @ThorTheDestroyer @mitchellryant

**Comment by mitchellryant** [comment]
@LaurenKirk @ThorTheDestroyer 

@creinier-TxGIO has been added to the repo!

**Comment by creinier-TxGIO** [comment]
Hi! After talking with Lauren we found that in addition to Harris County; McLennan, Nueces and Tyler also needed attributes remapped. These have been completed and uploaded to: \\gorgoroth\incomingdata\lp\2023_collection\updated_counties

After discussing with Joey and Lauren, we believe that issues with schema mapping for Harris County are likely resulting from the size of that shapefile. Because of this, we have split Harris County into 2 shapefiles: harris_east and harris_west. @mitchellryant @ThorTheDestroyer @LaurenKirk

**Comment by mitchellryant** [comment]
@creinier-TxGIO after the data has been transformed, it still needs to loaded to the data share and to the download location.  The issue was originally opened for Ector which has been replaced in both locations  

i see updated shp files for the 4 counties, are we updating the fgdb too?

**Comment by creinier-TxGIO** [comment]
@mitchellryant - new fgdbs have been uploaded. For Harris County, the fgdb only contains one feature class. It wasn't split like the shapefiles.

**Comment by mitchellryant** [comment]
complete
